Rename width to W in ver/clkdiv/test.v
It was renamed in commit cbcfc3ca631f in hdl/jt49_div.v. This fixes:

	test.v:36: error: parameter `width` not found in `test.uut`.
	2 error(s) during elaboration.