Rename cen_div to div in ver/clkdiv/test.v
It was renamed in commit 402d401e8bb9 in hdl/jt49_div.v. This fixes:

	test.v:36: error: port ``cen_div'' is not a port of uut.
	1 error(s) during elaboration.